# Generated by Django 2.2.4 on 2019-08-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('cover', models.ImageField(upload_to='images/home/')),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('cover', models.ImageField(upload_to='images/kids/')),
            ],
        ),
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('cover', models.ImageField(upload_to='images/womens/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Mens',
        ),
    ]
