# Generated by Django 2.2.4 on 2019-08-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190821_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
        migrations.RenameModel(
            old_name='Mens',
            new_name='Men',
        ),
        migrations.RenameModel(
            old_name='Womens',
            new_name='Women',
        ),
    ]
