# Generated by Django 2.2.4 on 2019-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190821_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='upload 2000x800 size', max_length=50)),
                ('cover', models.ImageField(upload_to='images/post/')),
            ],
        ),
    ]
