# Generated by Django 2.2.4 on 2019-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_home_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='gender', max_length=50)),
                ('cover', models.ImageField(upload_to='images/post/')),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
